number of integer and binary variables are also retrieved
SCIP-Interfaces/PySCIPOpt pull request #446
Opened 2020-10-26 21:39 UTC by ozancakiroglu95

2020-10-27 07:22 UTC, fserra requested changes
thanks!

2020-10-27 07:22 UTC, fserra commented on src/pyscipopt/scip.pyx
> +        """Retrieve the number of integer variables"""
```suggestion
        """gets number of integer active problem variables"""
```

2020-10-27 07:22 UTC, fserra commented on src/pyscipopt/scip.pyx
> +        """Retrieve the number of binary variables"""
```suggestion
        """gets number of binary active problem variables"""
```

2020-10-27 13:01 UTC, fserra approved these changes

2020-10-30 09:10 UTC, merged

2020-10-30 09:10 UTC, fserra commented
thanks for your contribution

2020-10-30 12:57 UTC, ozancakiroglu95 commented
I appreciate your interest. Thank you, too..